monolog:
    channels:
        - api
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: warning
                channels: ["!event", "!api", "!request"]
                formatter: App\Shared\Logging\SlimLineFormatter
            api:
                type: stream
                path: "%kernel.logs_dir%/api_%kernel.environment%.log"
                level: info
                channels: ["api"]
                formatter: App\Shared\Logging\SlimLineFormatter
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: warning
                channels: ["!event", "!api", "!request"]
                formatter: App\Shared\Logging\SlimLineFormatter
            api:
                type: stream
                path: "%kernel.logs_dir%/api_%kernel.environment%.log"
                level: info
                channels: ["api"]
                formatter: App\Shared\Logging\SlimLineFormatter

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!deprecation", "!api", "!request"]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: warning
                formatter: App\Shared\Logging\SlimLineFormatter
            api:
                type: stream
                path: "%kernel.logs_dir%/api_%kernel.environment%.log"
                level: info
                channels: ["api"]
                formatter: App\Shared\Logging\SlimLineFormatter
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecations_%kernel.environment%.log"
                formatter: App\Shared\Logging\SlimLineFormatter
