parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Shared\Logging\ExceptionLogger:
        arguments:
            $logger: '@monolog.logger.api'

    App\Shared\HttpKernel\ExceptionListener:
        tags:
            - { name: kernel.event_subscriber }

    App\Shared\EventSubscriber\:
        resource: '../src/Shared/EventSubscriber/'
        tags: ['kernel.event_subscriber']
